services:
  web:
    container_name: calendarioLunar_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:80"
    volumes:
      - node_modules:/app/node_modules
      - .:/app

volumes:
  node_modules:
