services:
  web:
    container_name: calendarioLunar_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    volumes:
      - node_modules:/app/node_modules
    environment:
      - PORT=80

volumes:
  node_modules:
